# Copyright 2025 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://www.schemastore.org/github-action.json

name: Install dependencies
description: Install the system dependencies
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - name: Install protobuf
      shell: bash
      env:
        PB_REL: "https://github.com/protocolbuffers/protobuf/releases"
        PB_VERSION: "30.2"
      run: |
        mkdir -p "$HOME/.local/cache"
        cd "$HOME/.local/cache"
        curl -OL "$PB_REL/download/v$PB_VERSION/protoc-$PB_VERSION-linux-x86_64.zip"
        unzip "protoc-$PB_VERSION-linux-x86_64.zip" -d "$HOME/.local"
        echo "PATH=\"$PATH:$HOME/.local/bin\"" >> "$GITHUB_ENV"
